"""Extract user-facing CLI text into a deterministic corpus for STE checking.

Collects the Typer/help one-line command help, the global option help strings,
and the static messages of every stable ``CliError`` factory (message and hint),
then writes them as Markdown to a corpus file. Running the CLI's own strings
through Vale and ``check_ste.py`` keeps help, prompts, warnings, errors, and
hints inside the same house style as the guides. Output is sorted, so a
regenerated corpus is diff-stable.

Usage: ``python scripts/extract_cli_text.py [OUTPUT]`` (default:
``build/cli-text-corpus.md`` under the package).
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from mammoth_cli import errors  # noqa: E402
from mammoth_cli.errors import envelope  # noqa: E402
from mammoth_cli.manifest.loader import load_commands  # noqa: E402
from mammoth_cli.runtime import options  # noqa: E402

_DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "build" / "cli-text-corpus.md"


def _error_sentences() -> list[str]:
    """Collect message/hint text from the zero-argument CliError factories."""
    sentences: list[str] = []
    for name in sorted(dir(envelope)):
        factory = getattr(envelope, name)
        if not (callable(factory) and name.endswith("_error")):
            continue
        try:
            error = factory()  # only zero-argument factories
        except TypeError:
            continue
        if isinstance(error, errors.envelope.CliError):
            sentences.append(error.message)
            if error.hint:
                sentences.append(error.hint)
    return sentences


def _command_help() -> list[str]:
    """Collect the manifest known-restriction help lines, if any."""
    lines: list[str] = []
    for record in load_commands():
        restriction = record.get("known_restrictions")
        if restriction:
            lines.append(str(restriction))
    return lines


def _option_help() -> list[str]:
    """Collect the shared global-option help strings."""
    helps: list[str] = []
    for name in dir(options):
        if name.endswith("_option"):
            option = getattr(options, name)()
            help_text = getattr(option, "help", None)
            if help_text:
                helps.append(str(help_text))
    return helps


def build_corpus() -> str:
    """Render the deterministic CLI-text corpus."""
    blocks = {
        "Command help": _command_help(),
        "Option help": _option_help(),
        "Error messages and hints": _error_sentences(),
    }
    lines = ["# CLI text corpus", "", "Generated by scripts/extract_cli_text.py.", ""]
    for title, items in blocks.items():
        lines.append(f"## {title}")
        lines.append("")
        for item in sorted(set(items)):
            lines.append(item if item.rstrip().endswith((".", "!", "?")) else f"{item}.")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write the corpus to the output path (default under ``build/``)."""
    args = argv if argv is not None else sys.argv[1:]
    output = Path(args[0]) if args else _DEFAULT_OUTPUT
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_corpus(), encoding="utf-8")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
