"""Explain Mammoth to the model, on demand.

The server is stateless and its instructions are short, so a client that needs
more than the tool descriptions asks for a topic here instead of paying for the
whole explanation on every request.
"""

from mcp.server.mcpserver.exceptions import ToolError

from ..sdk import JsonValue
from ..server import mcp_server

HELP_TOPICS: dict[str, str] = {
    "overview": (
        """\
# Mammoth Analytics

Data is organised as **workspace > project > dataset > view**.

- A **workspace** is the top level of an account. It owns projects and members.
- A **project** groups datasets that belong together.
- A **dataset** is data brought in, for example an uploaded file or a connector
  import. A dataset always has at least one view.
- A **view** is a lens on a dataset. Read data and run transformations against a
  view, never against the dataset itself. Views over one dataset share the data
  but each has its own pipeline, so a second view is the safe place to
  experiment.

Every tool takes the ids of the whole path — workspace, project, dataset, view —
because the server keeps no "current project" between calls. A Mammoth link the
user pastes carries them as `/<plural>/<id>` pairs, so read them off it:
`https://app.mammoth.io/#/workspaces/11/projects/98/datasets/1200/views/1039`
is workspace 11, project 98, dataset 1200, view 1039.

Start with `list_workspaces`, then `list_projects`, `list_datasets`,
`list_views`. Call `get_view` before writing anything that names a column.
"""
    ),
    "columns": (
        """\
# Columns

Each column has two names:

- a **display name**, which the user sees and talks about, and
- an **internal name**, generated by Mammoth, e.g. `column_qklgqhtw6v`.

Tools take internal names. `get_view` reports both, so look the column up there
before you name it — display names change when the data is transformed.

Column types are TEXT, NUMERIC, DATE and DATETIME. The type decides what can be
done with a column: dates uploaded from a CSV arrive as TEXT and have to be
converted before any date operation works.
"""
    ),
}


@mcp_server.tool()
async def get_help(topic: str) -> dict[str, JsonValue]:
    """Explain how Mammoth works. Read this before a first transformation.

    Args:
        topic: Which topic to explain. One of: overview, columns.
    """
    if topic not in HELP_TOPICS:
        raise ToolError(f"No help topic '{topic}'. Topics: {', '.join(HELP_TOPICS)}")
    return {"topic": topic, "help": HELP_TOPICS[topic]}
